# The base URL of the site
base_url = "https://defermelowie.github.io"

# Meta info about the site
title = "defermelowie"
author = "Lowie Deferme"

# General configuration
theme = "apollo"
taxonomies = [{ name = "tags" }]

# Generate outputs
minify_html = true
build_search_index = true
generate_robots_txt = true
generate_sitemap = true

# Configuration of the Markdown rendering
[markdown]

# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Configuration of search function
[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the RFC3339 datetime of the page in the search index
include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
# theme ∈ {"light", "dark", "auto", "toggle"}
theme = "toggle"

# Social links displayed in the header
socials = [
    { name = "GitHub", url = "https://github.com/defermelowie", icon = "github" },
    # { name = "Email", url = "mailto:lowie.deferme@kuleuven.be", icon = "mail" },
]

# Menu items
menu = [
    { name = "/home", url = "@/_index.md" },
    { name = "/posts", url = "@/post/_index.md" },
    { name = "/about", url = "@/about.md" },
    # { name = "About", url = "@/about/_index.md" },
]

# Site settings
homepage_layout = "about" # "about" or "list"

# Configuration of the link checker.
[link_checker]

# Treat internal link problems as either "error" or "warn", default is "error"
internal_level = "error"

# Treat external link problems as either "error" or "warn", default is "error"
external_level = "error"
