# The base URL of the site
base_url = "https://defermelowie.github.io"

# Meta info about the site
title = "defermelowie"
author = "Lowie Deferme"

# General configuration
theme = "apollo"
taxonomies = [{ name = "tags" }]

# Generate outputs
minify_html = true
build_search_index = true
generate_robots_txt = true
generate_sitemap = true

# Configuration of the Markdown rendering
[markdown]

# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]
extra_syntaxes_and_themes = ["syntax"]

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

github_alerts = true

# Configuration of search function
[search]
include_path = false
include_title = true
include_date = false
include_description = true
include_content = true

[extra]
# Theme ∈ {"light", "dark", "auto", "toggle"}
theme = "toggle"

# Social links displayed in the header
socials = [
    { name = "GitHub", url = "https://github.com/defermelowie", icon = "github" },
    # { name = "Email", url = "mailto:lowie.deferme@kuleuven.be", icon = "mail" },
]

# Menu items
menu = [
    { name = "/home", url = "@/_index.md" },
    { name = "/posts", url = "@/post/_index.md" },
    { name = "/about", url = "@/about.md" },
]

# Theme specific
fancy_code = true
dynamic_note = true

# Configuration of the link checker.
[link_checker]

# Treat link problems as either "error" or "warn", default is "error"
internal_level = "error"
external_level = "error"
